Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/gallery'
  get 'welcome/about_us'
  get 'welcome/mission'
  get 'welcome/chairman_message'
  get 'welcome/principal_message'
  get 'welcome/mandatory_public_disclosure'
  get 'welcome/committee'
  get 'welcome/pta'
  get 'welcome/faculty'
  get 'welcome/oasis_updated'
  get 'welcome/result_date_sheet'
  get 'welcome/book_list'
  get 'welcome/admission_procedure'
  get 'welcome/prospectus'
  get 'welcome/noc'
  get 'welcome/recognition'
  get 'welcome/land_certificate'
  get 'welcome/water_certificate'
  get 'welcome/affiliation_letter'
  get 'welcome/fire_safety'
  get 'welcome/building_safety_certificate'

  get 'welcome/fee_stracture'
  get 'welcome/student_strength'
  get 'welcome/tc_entries'
  get 'welcome/activities_compatitions'
  get 'welcome/school_building'
  get 'welcome/transport_facilities'
  get 'welcome/class_room'
  get 'welcome/infirmary'
  get 'welcome/library'
  get 'welcome/laboratories'
  get 'welcome/photos'
  get 'welcome/videos'
  get 'welcome/contact_us'
  get 'welcome/feedback'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
